apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c20,c10
    openshift.io/sa.scc.supplemental-groups: 1000400000/10000
    openshift.io/sa.scc.uid-range: 1000400000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2023-03-23T06:24:29Z"
  labels:
    kubernetes.io/metadata.name: openshift-operators
    openshift.io/scc: anyuid
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
    security.openshift.io/scc.podSecurityLabelSync: "true"
  name: openshift-operators
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 0c16ab14-f8d3-4cbb-b51f-593eee715a4f
  resourceVersion: "641121"
  uid: 9f068941-8cb2-45b2-883a-ca626a04330a
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
