apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kiali.io/v1alpha1","kind":"Kiali","metadata":{"annotations":{"maistra.io/mesh-generation":"2.3.2-1-5"},"labels":{"app.kubernetes.io/component":"kiali","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"kiali","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"2.3.2-1-5","maistra-version":"2.3.2","maistra.io/owner":"istio-system","maistra.io/owner-name":"basic"},"name":"kiali","namespace":"istio-system","ownerReferences":[{"apiVersion":"maistra.io/v2","blockOwnerDeletion":true,"controller":true,"kind":"ServiceMeshControlPlane","name":"basic","uid":"ea62ab37-de81-47cf-a7a3-ecf2986a0b2f"}]},"spec":{"auth":{"strategy":"openshift"},"deployment":{"accessible_namespaces":[],"image_pull_policy":"","ingress":{"enabled":true},"namespace":"istio-system","resources":{"requests":{"cpu":"100m","memory":"256Mi"}}},"external_services":{"custom_dashboards":{"namespace_label":"kubernetes_namespace"},"grafana":{"auth":{"password":"01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa","type":"basic","use_kiali_token":false,"username":"internal"},"enabled":true,"in_cluster_url":"https://grafana.istio-system.svc:3000","url":"https://grafana-istio-system.apps.demos.sandbox686.opentlc.com"},"istio":{"config_map_name":"istio-basic","istio_sidecar_injector_config_map_name":"istio-sidecar-injector-basic","istiod_deployment_name":"istiod-basic","url_service_version":"http://istiod-basic.istio-system:15014/version"},"prometheus":{"auth":{"password":"01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa","type":"basic","use_kiali_token":false,"username":"internal"},"url":"https://prometheus.istio-system.svc:9090"},"tracing":{"auth":{"password":"01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa","type":"basic","use_kiali_token":false,"username":"internal"},"enabled":true,"in_cluster_url":"https://jaeger-query.istio-system.svc","namespace":"istio-system","service":"","url":"https://jaeger-istio-system.apps.demos.sandbox686.opentlc.com","use_grpc":false}},"installation_tag":"Kiali [istio-system]","istio_namespace":"istio-system","server":{"web_root":"/dashboards/kiali"},"version":"v1.57"}}
    maistra.io/mesh-generation: 2.3.2-1-5
  creationTimestamp: "2023-03-24T17:28:26Z"
  finalizers:
  - kiali.io/finalizer
  generation: 3
  labels:
    app.kubernetes.io/component: kiali
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.3.2-1-5
    maistra-version: 2.3.2
    maistra.io/owner: istio-system
    maistra.io/owner-name: basic
  name: kiali
  namespace: istio-system
  ownerReferences:
  - apiVersion: maistra.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: ServiceMeshControlPlane
    name: basic
    uid: ea62ab37-de81-47cf-a7a3-ecf2986a0b2f
  resourceVersion: "1758858"
  uid: 82801f48-a75a-4d8c-ba65-484585db7382
spec:
  api:
    namespaces:
      exclude: []
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces:
    - cascade-openshifty
    - istio-samples
    image_pull_policy: ""
    ingress:
      enabled: true
    namespace: istio-system
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
  external_services:
    custom_dashboards:
      namespace_label: kubernetes_namespace
    grafana:
      auth:
        password: 01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: https://grafana.istio-system.svc:3000
      url: https://grafana-istio-system.apps.demos.sandbox686.opentlc.com
    istio:
      config_map_name: istio-basic
      istio_sidecar_injector_config_map_name: istio-sidecar-injector-basic
      istiod_deployment_name: istiod-basic
      url_service_version: http://istiod-basic.istio-system:15014/version
    prometheus:
      auth:
        password: 01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa
        type: basic
        use_kiali_token: false
        username: internal
      url: https://prometheus.istio-system.svc:9090
    tracing:
      auth:
        password: 01nOPFax5TTEXjzl35lWfrrikw1INc4colptV5og4hRqtFM5WZmjhwQNWSknQjpIwCy1/DFXkgNrUy2sKPmfZvyattseoESw6ItDqNwRMMPlA31B6OrSPt6EIPXb7ykbYiNT3RjCmNQr2kiLfXSOiAHUcAqmbGyWk8jDUpv+YaWwo8Uz0Nraax3HeEIAlBF5jcAPVa1iZgepsRWUyw1pfbez4iOn3QWKsHYBozsRm6BmoIwhxMsEdJCVPpPodhiIayXR1abudy0KxhdDYihGkXZhQuWi52s5SBQ/QmtyAEJC/CkxJqSinn2YVGVkC0T3AavOtdMJkQgbV1O0MgCa
        type: basic
        use_kiali_token: false
        username: internal
      enabled: true
      in_cluster_url: https://jaeger-query.istio-system.svc
      namespace: istio-system
      service: ""
      url: https://jaeger-istio-system.apps.demos.sandbox686.opentlc.com
      use_grpc: false
  installation_tag: Kiali [istio-system]
  istio_namespace: istio-system
  server:
    web_root: /dashboards/kiali
  version: v1.57
status:
  conditions:
  - lastTransitionTime: "2023-03-24T17:28:56Z"
    message: ""
    reason: ""
    status: "False"
    type: Failure
  - ansibleResult:
      changed: 8
      completion: 2023-03-26T03:08:55.739567
      failures: 0
      ok: 126
      skipped: 89
    lastTransitionTime: "2023-03-24T17:28:26Z"
    message: Awaiting next reconciliation
    reason: Successful
    status: "True"
    type: Running
  - lastTransitionTime: "2023-03-26T03:08:55Z"
    message: Last reconciliation succeeded
    reason: Successful
    status: "True"
    type: Successful
  deployment:
    accessibleNamespaces: istio-samples,istio-system
    instanceName: kiali
    namespace: istio-system
  environment:
    isMaistra: true
    isOpenshift: true
    kubernetesVersion: 1.25.4+a34b9e9
    openshiftVersion: 4.12.2
    operatorVersion: v1.57.6
  progress:
    duration: "0:00:26"
    message: 8. Finished all resource creation
  specVersion: v1.57
