---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "kiali.io/v1alpha1",
          "kind": "Kiali",
          "metadata": {
            "name": "kiali"
          },
          "spec": {
            "installation_tag": "My Kiali",
            "istio_namespace": "istio-system",
            "deployment": {
              "logger": {
                "log_level": "debug"
              },
              "namespace": "istio-system",
              "view_only_mode": false
            }
          }
        },
        {
          "apiVersion": "monitoring.kiali.io/v1alpha1",
          "kind": "MonitoringDashboard",
          "metadata": {
            "name": "myappdashboard"
          },
          "spec": {
            "title": "My App Dashboard",
            "items": [
              {
                "chart": {
                  "name": "My App Processing Duration",
                  "unit": "seconds",
                  "spans": 6,
                  "metricName": "my_app_duration_seconds",
                  "dataType": "histogram",
                  "aggregations": [
                    {
                      "label": "id",
                      "displayName": "ID"
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    capabilities: Deep Insights
    categories: Monitoring,Logging & Tracing
    certified: "false"
    containerImage: registry.redhat.io/openshift-service-mesh/kiali-rhel8-operator@sha256:052be81414c598a9b68edde275564757a476a2ea1014baefcb0ad4ec80e7eaf9
    createdAt: "2023-02-16T17:29:55Z"
    description: 'Kiali project provides answers to the questions: What microservices
      are part of my Istio service mesh and how are they connected?'
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.36/23"],"mac_address":"0a:58:0a:80:02:24","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.36/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.36"
          ],
          "mac": "0a:58:0a:80:02:24",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.36"
          ],
          "mac": "0a:58:0a:80:02:24",
          "default": true,
          "dns": {}
      }]
    olm.operatorGroup: global-operators
    olm.operatorNamespace: openshift-operators
    olm.skipRange: '>=1.0.0 <1.57.6'
    olm.targetNamespaces: ""
    openshift.io/scc: restricted-v2
    operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"kiali.io","kind":"Kiali","version":"v1alpha1"}},{"type":"olm.gvk","value":{"group":"monitoring.kiali.io","kind":"MonitoringDashboard","version":"v1alpha1"}},{"type":"olm.package","value":{"packageName":"kiali-ossm","version":"1.57.6"}}]}'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    prometheus.io/scrape: "true"
    repository: https://github.com/kiali/kiali
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    support: Red Hat
  creationTimestamp: "2023-03-24T11:06:11Z"
  generateName: kiali-operator-785fc766fb-
  labels:
    app: kiali-operator
    app.kubernetes.io/name: kiali-operator
    app.kubernetes.io/part-of: kiali-operator
    app.kubernetes.io/version: v1.57.6
    name: kiali-operator
    pod-template-hash: 785fc766fb
    version: v1.57.6
  name: kiali-operator-785fc766fb-vmgzp
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kiali-operator-785fc766fb
    uid: a4635273-872a-4360-9aeb-52022f2816f4
  resourceVersion: "681751"
  uid: c336f072-cba3-49a0-a78e-4ed65bbc60dc
spec:
  containers:
  - args:
    - --zap-log-level=info
    - --leader-election-id=kiali-operator
    env:
    - name: WATCH_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['olm.targetNamespaces']
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: ALLOW_AD_HOC_KIALI_NAMESPACE
      value: "false"
    - name: ALLOW_AD_HOC_KIALI_IMAGE
      value: "false"
    - name: ALLOW_SECURITY_CONTEXT_OVERRIDE
      value: "false"
    - name: ALLOW_ALL_ACCESSIBLE_NAMESPACES
      value: "true"
    - name: ACCESSIBLE_NAMESPACES_LABEL
      value: maistra.io/member-of
    - name: PROFILE_TASKS_TASK_OUTPUT_LIMIT
      value: "100"
    - name: ANSIBLE_DEBUG_LOGS
      value: "True"
    - name: ANSIBLE_VERBOSITY_KIALI_KIALI_IO
      value: "1"
    - name: ANSIBLE_CONFIG
      value: /etc/ansible/ansible.cfg
    - name: RELATED_IMAGE_kiali_default
      value: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aeaa5
    - name: RELATED_IMAGE_kiali_v1_57
      value: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aeaa5
    - name: RELATED_IMAGE_kiali_v1_48
      value: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:c8cd296ebe80afc3046aa420f392c038e7739208f1e231a09893e6ad9e1dd341
    - name: RELATED_IMAGE_kiali_v1_36
      value: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:f63e855495e2a8d996ec4e85f41591e1147b15ba2683c2c0dcf5bc9219322105
    - name: RELATED_IMAGE_kiali_v1_24
      value: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:1a4b3539f1e5aa9a132b1e2f4beef86c2e421bc6c84c4f133b9378a9731e8f42
    - name: OPERATOR_CONDITION_NAME
      value: kiali-operator.v1.57.6
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel8-operator@sha256:052be81414c598a9b68edde275564757a476a2ea1014baefcb0ad4ec80e7eaf9
    imagePullPolicy: IfNotPresent
    name: operator
    ports:
    - containerPort: 8080
      name: http-metrics
      protocol: TCP
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000400000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/ansible-operator/runner
      name: runner
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sdfpr
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: kiali-operator-dockercfg-6d2q2
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000400000
    seLinuxOptions:
      level: s0:c20,c10
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: kiali-operator
  serviceAccountName: kiali-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir: {}
    name: runner
  - name: kube-api-access-sdfpr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://9818bf84964311141521f7b4bdf96a4b70c9c6d0434b0d263fcd5300a4953811
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel8-operator@sha256:052be81414c598a9b68edde275564757a476a2ea1014baefcb0ad4ec80e7eaf9
    imageID: registry.redhat.io/openshift-service-mesh/kiali-rhel8-operator@sha256:052be81414c598a9b68edde275564757a476a2ea1014baefcb0ad4ec80e7eaf9
    lastState: {}
    name: operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T11:06:19Z"
  hostIP: 10.0.156.53
  phase: Running
  podIP: 10.128.2.36
  podIPs:
  - ip: 10.128.2.36
  qosClass: Burstable
  startTime: "2023-03-24T11:06:11Z"
