---
apiVersion: autoscaling/v2
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2023-03-24T17:29:17Z"
    labels:
      app: jaeger
      app.kubernetes.io/component: hpa-collector
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/managed-by: jaeger-operator
      app.kubernetes.io/name: jaeger-collector
      app.kubernetes.io/part-of: jaeger
    name: jaeger-collector
    namespace: istio-system
    ownerReferences:
    - apiVersion: jaegertracing.io/v1
      controller: true
      kind: Jaeger
      name: jaeger
      uid: a54859a0-fa66-4a80-a933-0b3891856e7b
    resourceVersion: "1902910"
    uid: e279dbc5-5bd7-4cc6-bf32-88bb309d550a
  spec:
    maxReplicas: 100
    metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 90
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 90
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: jaeger-collector
  status:
    conditions:
    - lastTransitionTime: "2023-03-24T17:29:32Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2023-03-24T17:30:18Z"
      message: the HPA was able to successfully calculate a replica count from memory
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2023-03-24T17:30:18Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 21
          averageValue: "29167616"
        name: memory
      type: Resource
    - resource:
        current:
          averageUtilization: 0
          averageValue: "0"
        name: cpu
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
kind: HorizontalPodAutoscalerList
metadata:
  resourceVersion: "1903151"
