apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: https://keycloak-sso.apps.demos.sandbox686.opentlc.com/auth/realms/istio-samples
    jwksUri: https://keycloak-sso.apps.demos.sandbox686.opentlc.com/auth/realms/istio-samples/protocol/openid-connect/certs
  principalBinding: USE_ORIGIN