---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.istio.io/v1beta1","kind":"DestinationRule","metadata":{"annotations":{"maistra.io/mesh-generation":"2.3.2-1-5"},"labels":{"app":"jaeger","app.kubernetes.io/component":"tracing","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"tracing","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"2.3.2-1-5","maistra-version":"2.3.2","maistra.io/owner":"istio-system","maistra.io/owner-name":"basic","release":"istio"},"name":"disable-mtls-zipkin","namespace":"istio-system","ownerReferences":[{"apiVersion":"maistra.io/v2","blockOwnerDeletion":true,"controller":true,"kind":"ServiceMeshControlPlane","name":"basic","uid":"ea62ab37-de81-47cf-a7a3-ecf2986a0b2f"}]},"spec":{"host":"zipkin","trafficPolicy":{"tls":{"mode":"DISABLE"}}}}
    maistra.io/mesh-generation: 2.3.2-1-5
  creationTimestamp: "2023-03-24T17:28:23Z"
  generation: 1
  labels:
    app: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: tracing
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.3.2-1-5
    maistra-version: 2.3.2
    maistra.io/owner: istio-system
    maistra.io/owner-name: basic
    release: istio
  name: disable-mtls-zipkin
  namespace: istio-system
  ownerReferences:
  - apiVersion: maistra.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: ServiceMeshControlPlane
    name: basic
    uid: ea62ab37-de81-47cf-a7a3-ecf2986a0b2f
  resourceVersion: "886104"
  uid: 5a68a35b-cf41-42a7-8dea-3506cfb21c95
spec:
  host: zipkin
  trafficPolicy:
    tls:
      mode: DISABLE
status:
  conditions:
  - lastProbeTime: "2023-03-24T18:24:34.944900010Z"
    lastTransitionTime: "2023-03-24T18:24:34.944900213Z"
    message: 36/36 proxies up to date.
    status: "True"
    type: Reconciled
  observedGeneration: "1"
