---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.64/23"],"mac_address":"0a:58:0a:80:02:40","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.64/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.64"
          ],
          "mac": "0a:58:0a:80:02:40",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.64"
          ],
          "mac": "0a:58:0a:80:02:40",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-03-24T17:28:13Z"
  generateName: prometheus-6fdb86d67b-
  labels:
    app: prometheus
    maistra-control-plane: istio-system
    pod-template-hash: 6fdb86d67b
    release: istio
  name: prometheus-6fdb86d67b-rmxmk
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: prometheus-6fdb86d67b
    uid: d5011e78-4c23-4cfd-b6ec-a6ed90f52b07
  resourceVersion: "858138"
  uid: f6e410dd-209b-438e-ac74-1da81d13b8f8
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - -provider=openshift
    - -https-address=:3001
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -htpasswd-file=/etc/proxy/htpasswd/auth
    - -display-htpasswd-form=false
    - '-openshift-sar={"namespace": "istio-system", "resource": "pods", "verb": "get"}'
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -openshift-service-account=prometheus
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f968922564c3eea1c69d6bbe529d8970784d6cae8935afaf674d9fa7c0f72ea3
    imagePullPolicy: IfNotPresent
    name: prometheus-proxy
    ports:
    - containerPort: 3001
      name: https
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /oauth/healthz
        port: https
        scheme: HTTPS
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-prometheus-tls
    - mountPath: /etc/proxy/htpasswd
      name: secret-htpasswd
    - mountPath: /etc/proxy/secrets
      name: secret-prometheus-proxy
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: trusted-ca-bundle
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-w2fqc
      readOnly: true
  - args:
    - --storage.tsdb.retention.time=6h
    - --storage.tsdb.path=/prometheus
    - --config.file=/etc/prometheus/prometheus.yml
    - --discovery.member-roll-name=default
    - --discovery.member-roll-namespace=istio-system
    image: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:39224efbb0d80d1f59c290046c981008926a0bce90be25542958045938b9dfcd
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/healthy
        port: 9090
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: prometheus
    ports:
    - containerPort: 9090
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/ready
        port: 9090
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/prometheus
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-w2fqc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: prometheus-dockercfg-kcs4p
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000720000
    seLinuxOptions:
      level: s0:c27,c9
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: prometheus
  serviceAccountName: prometheus
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: secret-prometheus-tls
    secret:
      defaultMode: 420
      secretName: prometheus-tls
  - name: secret-htpasswd
    secret:
      defaultMode: 420
      secretName: htpasswd
  - name: secret-prometheus-proxy
    secret:
      defaultMode: 420
      secretName: prometheus-proxy
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: trusted-ca-bundle
      optional: true
    name: trusted-ca-bundle
  - configMap:
      defaultMode: 420
      name: istio-basic
      optional: true
    name: istio-config-volume
  - configMap:
      defaultMode: 420
      name: prometheus
    name: config-volume
  - name: kube-api-access-w2fqc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:28:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:28:22Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:28:22Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:28:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://a5e428951d71667475e09b8cb64d900a5732e79e2611b677fc9df3f2cddf7f04
    image: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:39224efbb0d80d1f59c290046c981008926a0bce90be25542958045938b9dfcd
    imageID: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:39224efbb0d80d1f59c290046c981008926a0bce90be25542958045938b9dfcd
    lastState: {}
    name: prometheus
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T17:28:21Z"
  - containerID: cri-o://78ad5ad5adc4f0d5a8fa08341ca3810bc8b4e5c27e46d31c47f5e3fb59150b78
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f968922564c3eea1c69d6bbe529d8970784d6cae8935afaf674d9fa7c0f72ea3
    imageID: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f968922564c3eea1c69d6bbe529d8970784d6cae8935afaf674d9fa7c0f72ea3
    lastState: {}
    name: prometheus-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T17:28:14Z"
  hostIP: 10.0.156.53
  phase: Running
  podIP: 10.128.2.64
  podIPs:
  - ip: 10.128.2.64
  qosClass: Burstable
  startTime: "2023-03-24T17:28:13Z"
