- name: install Red Hat OpenShift distributed tracing
  kubernetes.core.k8s:
    state: present
    api_key: "{{ api_key }}"      
    apply: true
    validate_certs: false
    resource_definition: "{{ lookup('template', './templates/subscription.yaml.j2') | from_yaml }}"

- name: wait for operator to be ready
  kubernetes.core.k8s_info:
    api_key: "{{ api_key }}"
    kind: ClusterServiceVersion
    name: jaeger-operator.v1.39.0-3
    api_version: operators.coreos.com/v1alpha1
    namespace: "{{ operators.jaeger.namespace }}"
  register: __jaeger_operator_install_result
  until: "(__jaeger_operator_install_result['resources'][0]['status']['phase'] is defined) and (__jaeger_operator_install_result['resources'][0]['status']['phase'] == 'Succeeded')"
  retries: 15
  delay: 15