---
apiVersion: discovery.k8s.io/v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.129.2.151
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-215-253.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: istio-operator-589bdfb57c-gldk4
      namespace: openshift-operators
      uid: 4cbd6928-6959-43d2-95c5-8c4938f5c162
    zone: us-west-2c
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2023-03-24T09:41:49Z"
    generateName: istio-operator-metrics-
    generation: 7
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: istio-operator-metrics
      name: istio-operator
    name: istio-operator-metrics-5fmn7
    namespace: openshift-operators
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: istio-operator-metrics
      uid: b915e6fe-01bc-4627-ba8f-a580b79fad08
    resourceVersion: "681738"
    uid: 240fe416-ccca-4f1f-9657-5eced31998a9
  ports:
  - name: cr-metrics
    port: 8686
    protocol: TCP
  - name: http-metrics
    port: 8383
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.129.2.151
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-215-253.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: istio-operator-589bdfb57c-gldk4
      namespace: openshift-operators
      uid: 4cbd6928-6959-43d2-95c5-8c4938f5c162
    zone: us-west-2c
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2023-03-24T09:41:46Z"
    generateName: maistra-admission-controller-
    generation: 7
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: maistra-admission-controller
    name: maistra-admission-controller-gxfth
    namespace: openshift-operators
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: maistra-admission-controller
      uid: 6bde54f0-d3f8-411d-b64d-9ff09e2ef14f
    resourceVersion: "681739"
    uid: fa047d33-d8bb-4bfa-9e14-99c3f858306a
  ports:
  - name: validation
    port: 11999
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.128.2.27
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-156-53.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: opentelemetry-operator-controller-manager-bfbf89c88-n7k8g
      namespace: openshift-operators
      uid: 8512dd9b-42d1-4a1f-81b8-090f17988ddf
    zone: us-west-2a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-03-24T09:33:58Z"
    creationTimestamp: "2023-03-24T09:33:20Z"
    generateName: opentelemetry-operator-controller-manager-metrics-service-
    generation: 3
    labels:
      app.kubernetes.io/name: opentelemetry-operator
      control-plane: controller-manager
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: opentelemetry-operator-controller-manager-metrics-service
      operators.coreos.com/opentelemetry-product.openshift-operators: ""
    name: opentelemetry-operator-controller-manager-metrics-service-6p8wx
    namespace: openshift-operators
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: opentelemetry-operator-controller-manager-metrics-service
      uid: e2096f8a-22c9-4f13-9505-0d600bdbc29c
    resourceVersion: "636827"
    uid: e8b3dd81-915a-4e86-8c36-b841bac1f88c
  ports:
  - name: https
    port: 8443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.128.2.27
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-156-53.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: opentelemetry-operator-controller-manager-bfbf89c88-n7k8g
      namespace: openshift-operators
      uid: 8512dd9b-42d1-4a1f-81b8-090f17988ddf
    zone: us-west-2a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-03-24T09:33:58Z"
    creationTimestamp: "2023-03-24T09:33:22Z"
    generateName: opentelemetry-operator-controller-manager-service-
    generation: 3
    labels:
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: opentelemetry-operator-controller-manager-service
      operators.coreos.com/opentelemetry-product.openshift-operators: ""
    name: opentelemetry-operator-controller-manager-service-spprw
    namespace: openshift-operators
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: opentelemetry-operator-controller-manager-service
      uid: e890db26-4d69-4b97-87e3-d37b6faf70e4
    resourceVersion: "636828"
    uid: 9182bf66-bc94-48e6-9aba-fe603f2c9163
  ports:
  - name: "443"
    port: 9443
    protocol: TCP
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 10.128.2.27
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: ip-10-0-156-53.us-west-2.compute.internal
    targetRef:
      kind: Pod
      name: opentelemetry-operator-controller-manager-bfbf89c88-n7k8g
      namespace: openshift-operators
      uid: 8512dd9b-42d1-4a1f-81b8-090f17988ddf
    zone: us-west-2a
  kind: EndpointSlice
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2023-03-24T09:33:58Z"
    creationTimestamp: "2023-03-24T09:33:19Z"
    generateName: opentelemetry-operator-webhook-service-
    generation: 3
    labels:
      app.kubernetes.io/name: opentelemetry-operator
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: opentelemetry-operator-webhook-service
      operators.coreos.com/opentelemetry-product.openshift-operators: ""
    name: opentelemetry-operator-webhook-service-kcncr
    namespace: openshift-operators
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: opentelemetry-operator-webhook-service
      uid: 08ca91e9-36f7-4e74-a759-da1c4a4be0db
    resourceVersion: "636826"
    uid: b0f3ebc7-bdf3-42d1-a410-a6848aae75a3
  ports:
  - name: ""
    port: 9443
    protocol: TCP
kind: EndpointSliceList
metadata:
  resourceVersion: "1903142"
