apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/sa.scc.mcs: s0:c27,c9
    openshift.io/sa.scc.supplemental-groups: 1000720000/10000
    openshift.io/sa.scc.uid-range: 1000720000/10000
  creationTimestamp: "2023-03-24T10:12:51Z"
  labels:
    kiali.io/member-of: istio-system
    kubernetes.io/metadata.name: istio-system
    maistra.io/ignore-namespace: ignore
    maistra.io/member-of: istio-system
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.24
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.24
  name: istio-system
  resourceVersion: "858918"
  uid: 0a57557a-5ab9-4955-aaae-5ac13078ac90
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
