---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.81/23"],"mac_address":"0a:58:0a:80:02:51","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.81/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.81"
          ],
          "mac": "0a:58:0a:80:02:51",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.81"
          ],
          "mac": "0a:58:0a:80:02:51",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    openshift.openshift.io/restartedAt: "2023-03-26T08:19:02.276Z"
    prometheus.io/port: "15014"
    prometheus.io/scrape: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-03-26T08:19:02Z"
  generateName: istiod-basic-6fc5ddbd5d-
  labels:
    app: istiod
    istio: istiod
    istio.io/rev: basic
    maistra-control-plane: istio-system
    pod-template-hash: 6fc5ddbd5d
    sidecar.istio.io/inject: "false"
  name: istiod-basic-6fc5ddbd5d-65slf
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istiod-basic-6fc5ddbd5d
    uid: e5793d6f-3ca4-43c2-9ec8-315a2da5d527
  resourceVersion: "1896102"
  uid: ba1e7d55-b51c-4adb-a6c9-9c00d31c43b9
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - discovery
    - --memberRollName=default
    - --disableNodeAccess=true
    - --enableCRDScan=false
    - --enableIngressClassName=false
    - --monitoringAddr=:15014
    - --log_output_level=default:warn
    - --log_as_json
    - --domain
    - cluster.local
    - --keepaliveMaxServerConnectionAge
    - 30m
    env:
    - name: ENABLE_IOR
      value: "false"
    - name: PRIORITIZED_LEADER_ELECTION
      value: "false"
    - name: VALIDATION_WEBHOOK_CONFIG_NAME
    - name: INJECTION_WEBHOOK_CONFIG_NAME
    - name: REVISION
      value: basic
    - name: JWT_POLICY
      value: first-party-jwt
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: KUBECONFIG
      value: /var/run/secrets/remote/config
    - name: PILOT_ENABLE_GATEWAY_API
      value: "false"
    - name: PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER
      value: "false"
    - name: PILOT_ENABLE_GATEWAY_API_STATUS
      value: "false"
    - name: PILOT_ENABLE_FEDERATION
      value: "true"
    - name: PILOT_TRACE_SAMPLING
      value: "1"
    - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_OUTBOUND
      value: "false"
    - name: PILOT_ENABLE_PROTOCOL_SNIFFING_FOR_INBOUND
      value: "false"
    - name: ISTIOD_ADDR
      value: istiod-basic.istio-system.svc:15012
    - name: PILOT_ENABLE_STATUS
      value: "true"
    - name: PILOT_ENABLE_ANALYSIS
      value: "true"
    - name: CLUSTER_ID
      value: Kubernetes
    image: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:daa1c9b3ffde151a2efb12a7a4bf4c9665dbd4a8be0490192c32a4e5532c0ad8
    imagePullPolicy: IfNotPresent
    name: discovery
    ports:
    - containerPort: 8080
      protocol: TCP
    - containerPort: 15010
      protocol: TCP
    - containerPort: 15017
      name: webhook
      protocol: TCP
    - containerPort: 8188
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/istio-dns
      name: local-certs
    - mountPath: /etc/cacerts
      name: cacerts
      readOnly: true
    - mountPath: /var/run/secrets/remote
      name: istio-kubeconfig
      readOnly: true
    - mountPath: /cacerts
      name: extracacerts
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-q8t4z
      readOnly: true
    workingDir: /
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: istiod-basic-dockercfg-c847q
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000720000
    seLinuxOptions:
      level: s0:c27,c9
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: istiod-basic
  serviceAccountName: istiod-basic
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - emptyDir:
      medium: Memory
    name: local-certs
  - name: cacerts
    secret:
      defaultMode: 420
      optional: true
      secretName: cacerts
  - name: istio-kubeconfig
    secret:
      defaultMode: 420
      optional: true
      secretName: istio-kubeconfig
  - configMap:
      defaultMode: 420
      name: pilot-jwks-extra-cacerts-basic
    name: extracacerts
  - name: kube-api-access-q8t4z
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-26T08:19:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-26T08:19:04Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-26T08:19:04Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-26T08:19:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://5bc197867054c03cf4ce8e9cabd82bb9db18cf8a28d5a5100ae09d3acb6612cc
    image: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:daa1c9b3ffde151a2efb12a7a4bf4c9665dbd4a8be0490192c32a4e5532c0ad8
    imageID: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:daa1c9b3ffde151a2efb12a7a4bf4c9665dbd4a8be0490192c32a4e5532c0ad8
    lastState: {}
    name: discovery
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-26T08:19:03Z"
  hostIP: 10.0.156.53
  phase: Running
  podIP: 10.128.2.81
  podIPs:
  - ip: 10.128.2.81
  qosClass: Burstable
  startTime: "2023-03-26T08:19:02Z"
