---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.70/23"],"mac_address":"0a:58:0a:80:02:46","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.70/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.70"
          ],
          "mac": "0a:58:0a:80:02:46",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.70"
          ],
          "mac": "0a:58:0a:80:02:46",
          "default": true,
          "dns": {}
      }]
    kiali.io/dashboards: go,kiali
    openshift.io/scc: restricted-v2
    operator.kiali.io/last-updated: Fri Mar 24 17:30:04 UTC 2023
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2023-03-24T17:30:04Z"
  generateName: kiali-6c47d88b48-
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aXXX
    pod-template-hash: 6c47d88b48
    version: b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aXXX
  name: kiali-6c47d88b48-fhksv
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kiali-6c47d88b48
    uid: 9793bff2-f0dd-496e-be8c-ed9893d1fc2a
  resourceVersion: "860635"
  uid: 0de269b8-acf5-459a-9cb0-3857fd40a7f0
spec:
  containers:
  - command:
    - /opt/kiali/kiali
    - -config
    - /kiali-configuration/config.yaml
    env:
    - name: ACTIVE_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: LOG_FORMAT
      value: text
    - name: LOG_LEVEL
      value: info
    - name: LOG_SAMPLER_RATE
      value: "1"
    - name: LOG_TIME_FIELD_FORMAT
      value: 2006-01-02T15:04:05Z07:00
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aeaa5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /dashboards/kiali/healthz
        port: api-port
        scheme: HTTPS
      initialDelaySeconds: 5
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    name: kiali
    ports:
    - containerPort: 20001
      name: api-port
      protocol: TCP
    - containerPort: 9090
      name: http-metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /dashboards/kiali/healthz
        port: api-port
        scheme: HTTPS
      initialDelaySeconds: 5
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kiali-configuration
      name: kiali-configuration
    - mountPath: /kiali-cert
      name: kiali-cert
    - mountPath: /kiali-secret
      name: kiali-secret
    - mountPath: /kiali-cabundle
      name: kiali-cabundle
    - mountPath: /kiali-override-secrets/login-token-signing-key
      name: login-token-signing-key
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-spgzc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: kiali-service-account-dockercfg-9vt6j
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000720000
    seLinuxOptions:
      level: s0:c27,c9
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: kiali-service-account
  serviceAccountName: kiali-service-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: kiali
    name: kiali-configuration
  - name: kiali-cert
    secret:
      defaultMode: 420
      secretName: kiali-cert-secret
  - name: kiali-secret
    secret:
      defaultMode: 420
      optional: true
      secretName: kiali
  - configMap:
      defaultMode: 420
      name: kiali-cabundle
    name: kiali-cabundle
  - name: login-token-signing-key
    secret:
      defaultMode: 420
      items:
      - key: key
        path: value.txt
      optional: false
      secretName: kiali-signing-key
  - name: kube-api-access-spgzc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:30:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:30:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:30:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:30:04Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://c0f2fdfe6c94b0ef5672ce65672b9c96474bf4ecd7068130ff9b527dc7887b9e
    image: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:b38ef0fd4444e449f7f6cf84f6aa7558d502c9e848181a936bc338cd0e4aeaa5
    imageID: registry.redhat.io/openshift-service-mesh/kiali-rhel8@sha256:1794453b96ced9d22eb62b0562ceb3d313966326e1f4c58812d630c96b768a0f
    lastState: {}
    name: kiali
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T17:30:05Z"
  hostIP: 10.0.156.53
  phase: Running
  podIP: 10.128.2.70
  podIPs:
  - ip: 10.128.2.70
  qosClass: Burstable
  startTime: "2023-03-24T17:30:04Z"
