---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: "[\n  {\n    \"apiVersion\": \"maistra.io/v2\",\n    \"kind\": \"ServiceMeshControlPlane\",\n
      \   \"metadata\": {\n      \"name\": \"basic\",\n      \"namespace\": \"control-plane-namespace\"\n
      \   },\n    \"spec\": {\n      \"version\": \"v2.3\",\n      \"tracing\": {\n
      \       \"type\": \"Jaeger\",\n        \"sampling\": 10000\n      },\n      \"policy\":
      {\n         \"type\": \"Istiod\"\n      },\n      \"telemetry\": {\n         \"type\":
      \"Istiod\"\n      },\n      \"addons\": {\n        \"jaeger\": {\n          \"install\":
      {\n            \"storage\": {\n              \"type\": \"Memory\"\n            }\n
      \         }\n        },\n        \"prometheus\": {\n          \"enabled\": true\n
      \       },\n        \"kiali\": {\n          \"enabled\": true\n        },\n
      \       \"grafana\": {\n          \"enabled\": true\n        }\n      }\n    }\n
      \ },\n  {\n    \"apiVersion\": \"maistra.io/v1\",\n    \"kind\": \"ServiceMeshMemberRoll\",\n
      \   \"metadata\": {\n      \"name\": \"default\",\n      \"namespace\": \"control-plane-namespace\"\n
      \   },\n    \"spec\": {\n      \"members\": [\n        \"your-project\",\n        \"another-of-your-projects\"
      \n      ]\n    }\n  },\n  {\n    \"apiVersion\": \"maistra.io/v1\",\n    \"kind\":
      \"ServiceMeshMember\",\n    \"metadata\": {\n      \"name\": \"default\",\n
      \     \"namespace\": \"application-namespace\"\n    },\n    \"spec\": {\n      \"controlPlaneRef\":
      {\n        \"name\": \"basic\",\n        \"namespace\": \"control-plane-namespace\"\n
      \     }\n    }\n  }\n]"
    capabilities: Seamless Upgrades
    categories: OpenShift Optional, Integration & Delivery
    certified: "false"
    containerImage: registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:281ab02124a2c5a2bb5d0b0172491f0f7a63e1127aff9786a8006aa8821e23dd
    createdAt: 2023-01-31T14:49:18EST
    description: The OpenShift Service Mesh Operator enables you to install, configure,
      and manage an instance of Red Hat OpenShift Service Mesh. OpenShift Service
      Mesh is based on the open source Istio project.
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.2.151/23"],"mac_address":"0a:58:0a:81:02:97","gateway_ips":["10.129.2.1"],"ip_address":"10.129.2.151/23","gateway_ip":"10.129.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.2.151"
          ],
          "mac": "0a:58:0a:81:02:97",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.2.151"
          ],
          "mac": "0a:58:0a:81:02:97",
          "default": true,
          "dns": {}
      }]
    oauth-proxy.name: oauth-proxy
    oauth-proxy.namespace: openshift
    oauth-proxy.query: "true"
    oauth-proxy.tag: v4.4
    olm.operatorGroup: global-operators
    olm.operatorNamespace: openshift-operators
    olm.relatedImage.v2_0.3scale-istio-adapter: registry.redhat.io/openshift-service-mesh/3scale-istio-adapter-rhel8@sha256:2a15cb70a8a3290467f552821b50730fa7eaf6339f4f0fd9032cf2fe12d5c602
    olm.relatedImage.v2_0.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:161b3438a666469b230602b85d5c207f0f225210b5ba18c6ee7b9ae08127af23
    olm.relatedImage.v2_0.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:e614e9aa8e786a3ed31df6eacf6cf1ad556add4b272f61cdca7576da6cced838
    olm.relatedImage.v2_0.mixer: registry.redhat.io/openshift-service-mesh/mixer-rhel8@sha256:37b20c87bca153bcf435ffeb71b1b0e75ba190bae14d198c196993c5c48a64ec
    olm.relatedImage.v2_0.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:12284ec4fd6a02cfa82574469d022493688169ea09348ff1fd0b6170663b2956
    olm.relatedImage.v2_0.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:83dac7a5efd60d399f3ca0cc322727f88c2f9d93837e39c8800ed0d4ceeca01e
    olm.relatedImage.v2_0.proxy-init: registry.redhat.io/openshift-service-mesh/proxy-init-rhel7@sha256:ee45a4a595ed491ce318d88dd90e0308c59131c67598afc7c67da601f3e5fb92
    olm.relatedImage.v2_0.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:8471869e66a98bd44c9730bb50d82827a6c17a68cdd6cb8fdaeeee6eccf92029
    olm.relatedImage.v2_0.wasm-cacher: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:12284ec4fd6a02cfa82574469d022493688169ea09348ff1fd0b6170663b2956
    olm.relatedImage.v2_1.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:a9b51d0da38a7ae0423e74c4ed0c1dcc8140770ca34075944d73dea180f95418
    olm.relatedImage.v2_1.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:63cd675267e90bb02e13e57ce1b1ff3b3a21831281e1a6ecf3ad51cfe161c02c
    olm.relatedImage.v2_1.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:b2a7d16998e501bac06b0f9cac94999a795be31895163e88423638ea1f638435
    olm.relatedImage.v2_1.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:841f8bad415843f9a579f509b8a4c2ed0f4fb56f1cea2a6b5b8704900761a42f
    olm.relatedImage.v2_1.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:a9cb8adc2edfd4a42b64d2041ee58b1fd0068af0cd8cbbb0ef36a032725fd9c8
    olm.relatedImage.v2_1.rls: registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:f2c395c94dd63ab1aced5b1e3a220bc16326b0f516af933c30db57024cea2d7d
    olm.relatedImage.v2_1.wasm-cacher: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:b2a7d16998e501bac06b0f9cac94999a795be31895163e88423638ea1f638435
    olm.relatedImage.v2_2.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:14d035b9831a067789b3e9f78edc366e68f75b21fb509fe48790add37ec4f06f
    olm.relatedImage.v2_2.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:92e3081ac0e1a85bfe1b8c2c4f1716962298c0ad13b72cc1123ccad33931b070
    olm.relatedImage.v2_2.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:2f497fe3733affedc9b3b079afddf27e50065e4da06d07e983c85a5b05c76606
    olm.relatedImage.v2_2.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:d26dc44bc5a7b286bb41675a260b3a2a6ff9c17b0146725a66ad8b29a307c5d4
    olm.relatedImage.v2_2.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:b654eaaecb7d697b315e0d6a27b1d8499711241bd7dbbc1ea22f592aee99195e
    olm.relatedImage.v2_2.rls: registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:7a37e6ed4a7d206b819d4b5024181dd61fd0650b4f1db67fabd63b81920a23aa
    olm.relatedImage.v2_2.wasm-cacher: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:2f497fe3733affedc9b3b079afddf27e50065e4da06d07e983c85a5b05c76606
    olm.relatedImage.v2_3.cni: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:f967420e0e30c1193f6e766885e1e00a8a97e6929cf0d06cccd60649ff46610c
    olm.relatedImage.v2_3.grafana: registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:6c4b1ec87fdb6259a9845ac8530b7a6ea249acc2ba205ed79a6aa9a639d1a18f
    olm.relatedImage.v2_3.pilot: registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:daa1c9b3ffde151a2efb12a7a4bf4c9665dbd4a8be0490192c32a4e5532c0ad8
    olm.relatedImage.v2_3.prometheus: registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:39224efbb0d80d1f59c290046c981008926a0bce90be25542958045938b9dfcd
    olm.relatedImage.v2_3.proxyv2: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:15444e6b93a05d88c6fc6ce1d1e7744635141291b86a7c3abb57758849a5d19e
    olm.relatedImage.v2_3.rls: registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:12aaa9c8c84214fbffbd6a0e193bb84b9ad6bb64ddecbe06e1700cd184218214
    olm.skipRange: '>=1.0.2 <2.3.2-0'
    olm.targetNamespaces: ""
    openshift.io/scc: restricted-v2
    operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshControlPlane","version":"v1"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshControlPlane","version":"v2"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshMember","version":"v1"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshMemberRoll","version":"v1"}},{"type":"olm.package","value":{"packageName":"servicemeshoperator","version":"2.3.2-0"}}]}'
    operators.openshift.io/infrastructure-features: '["Disconnected"]'
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    repository: https://github.com/maistra/istio-operator
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    support: Red Hat, Inc.
  creationTimestamp: "2023-03-24T11:06:14Z"
  generateName: istio-operator-589bdfb57c-
  labels:
    name: istio-operator
    pod-template-hash: 589bdfb57c
  name: istio-operator-589bdfb57c-gldk4
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: istio-operator-589bdfb57c
    uid: a0f1bc4a-ba9e-4f6e-afa4-083c1942b6a5
  resourceVersion: "681691"
  uid: 4cbd6928-6959-43d2-95c5-8c4938f5c162
spec:
  containers:
  - command:
    - istio-operator
    - --config
    - /etc/operator/olm/config.properties
    env:
    - name: WATCH_NAMESPACE
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OPERATOR_NAME
      value: istio-operator
    - name: OPERATOR_CONDITION_NAME
      value: servicemeshoperator.v2.3.2
    image: registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:281ab02124a2c5a2bb5d0b0172491f0f7a63e1127aff9786a8006aa8821e23dd
    imagePullPolicy: Always
    name: istio-operator
    ports:
    - containerPort: 11999
      name: validation
      protocol: TCP
    - containerPort: 60000
      name: metrics
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000400000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/operator/olm
      name: operator-olm-config
      readOnly: true
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: webhook-tls-volume
      readOnly: true
    - mountPath: /usr/local/share/istio-operator/templates/
      name: smcp-templates
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sn7g2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: istio-operator-dockercfg-q9nlb
  nodeName: ip-10-0-215-253.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000400000
    seLinuxOptions:
      level: s0:c20,c10
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: istio-operator
  serviceAccountName: istio-operator
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: config.properties
    name: operator-olm-config
  - name: webhook-tls-volume
    secret:
      defaultMode: 420
      optional: true
      secretName: maistra-operator-serving-cert
  - configMap:
      defaultMode: 420
      name: smcp-templates
      optional: true
    name: smcp-templates
  - name: kube-api-access-sn7g2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:14Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:06:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://69b75143fbaeb3e21230943e34b3ad555e157d15361c7e53156260293ac4ed8e
    image: registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:281ab02124a2c5a2bb5d0b0172491f0f7a63e1127aff9786a8006aa8821e23dd
    imageID: registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:0efbfe363d9104480489e0c431ae264f91d4ec432b1f14feccde3a3a1067013b
    lastState: {}
    name: istio-operator
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T11:06:18Z"
  hostIP: 10.0.215.253
  phase: Running
  podIP: 10.129.2.151
  podIPs:
  - ip: 10.129.2.151
  qosClass: BestEffort
  startTime: "2023-03-24T11:06:14Z"
