---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.0.173/23"],"mac_address":"0a:58:0a:81:00:ad","gateway_ips":["10.129.0.1"],"ip_address":"10.129.0.173/23","gateway_ip":"10.129.0.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.0.173"
          ],
          "mac": "0a:58:0a:81:00:ad",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.0.173"
          ],
          "mac": "0a:58:0a:81:00:ad",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: privileged
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-03-24T11:07:43Z"
  generateName: istio-cni-node-v2-3-
  labels:
    controller-revision-hash: 5d8775b8fd
    k8s-app: istio-cni-node-v2-3
    pod-template-generation: "2"
    release: istio
  name: istio-cni-node-v2-3-sbtqp
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: istio-cni-node-v2-3
    uid: 7d34902b-b3e3-4617-a88d-3256a9bf7f59
  resourceVersion: "683309"
  uid: 37a62108-f2fd-4dd6-bac2-e4e1f20387fd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-10-0-140-16.us-west-2.compute.internal
  containers:
  - command:
    - install-cni
    env:
    - name: CNI_CONF_NAME
      value: v2-3-istio-cni.conf
    - name: CNI_NETWORK_CONFIG
      valueFrom:
        configMapKeyRef:
          key: cni_network_config
          name: istio-cni-config-v2-3
    - name: CNI_NET_DIR
      value: /etc/cni/multus/net.d
    - name: CHAINED_CNI_PLUGIN
      value: "false"
    - name: MOUNTED_CNI_NET_DIR
      value: /host/etc/cni/multus/net.d
    - name: KUBECFG_FILE_NAME
      value: v2-3-istio-cni.kubeconfig
    - name: CNI_BINARIES_PREFIX
      value: v2-3-
    image: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:f967420e0e30c1193f6e766885e1e00a8a97e6929cf0d06cccd60649ff46610c
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: install-cni
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8000
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/opt/cni/bin
      name: cni-bin-dir
    - mountPath: /host/etc/cni/
      name: etc-cni-dir
    - mountPath: /var/run/istio-cni
      name: cni-log-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n72ph
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: istio-cni-dockercfg-74lch
  nodeName: ip-10-0-140-16.us-west-2.compute.internal
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: istio-cni
  serviceAccountName: istio-cni
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /opt/multus/bin
      type: ""
    name: cni-bin-dir
  - hostPath:
      path: /etc/cni
      type: ""
    name: etc-cni-dir
  - hostPath:
      path: /var/run/istio-cni
      type: ""
    name: cni-log-dir
  - name: kube-api-access-n72ph
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:07:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:07:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:07:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T11:07:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://3ef664e76c100394708f4646138a935640f15091057f9f5290c12fdcac3876a4
    image: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:f967420e0e30c1193f6e766885e1e00a8a97e6929cf0d06cccd60649ff46610c
    imageID: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:b84c8f922f4fdf1fafcc39d54f067ac2b195d5eb9a49271e7a72ee2623beee5b
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T11:07:49Z"
  hostIP: 10.0.140.16
  phase: Running
  podIP: 10.129.0.173
  podIPs:
  - ip: 10.129.0.173
  qosClass: Burstable
  startTime: "2023-03-24T11:07:43Z"
