---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.78/23"],"mac_address":"0a:58:0a:80:02:4e","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.78/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.78"
          ],
          "mac": "0a:58:0a:80:02:4e",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.78"
          ],
          "mac": "0a:58:0a:80:02:4e",
          "default": true,
          "dns": {}
      }]
    linkerd.io/inject: disabled
    openshift.io/scc: restricted-v2
    prometheus.io/scrape: "false"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-03-25T23:55:00Z"
  generateName: jaeger-es-index-cleaner-27996475-
  labels:
    app: jaeger
    app.kubernetes.io/component: cronjob-es-index-cleaner
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-es-index-cleaner
    app.kubernetes.io/part-of: jaeger
    controller-uid: c2a0def7-183a-4161-bffd-cb9d6c9b022b
    job-name: jaeger-es-index-cleaner-27996475
  name: jaeger-es-index-cleaner-27996475-bdz5c
  namespace: istio-system
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: jaeger-es-index-cleaner-27996475
    uid: c2a0def7-183a-4161-bffd-cb9d6c9b022b
  resourceVersion: "1672732"
  uid: f78a51a3-d6fc-4648-90ac-a469f0f05d2b
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - "2"
    - https://elasticsearch:9200
    env:
    - name: SKIP_DEPENDENCIES
      value: "true"
    - name: ES_TLS_ENABLED
      value: "true"
    - name: ES_TLS_CA
      value: /certs/ca
    - name: ES_TLS_KEY
      value: /certs/key
    - name: ES_TLS_CERT
      value: /certs/cert
    - name: SHARDS
      value: "3"
    - name: REPLICAS
      value: "1"
    image: registry.redhat.io/rhosdt/jaeger-es-index-cleaner-rhel8@sha256:0065bf16da7fdf11c018388a4eb33349610129ea0465491d2bb6b24c275621dc
    imagePullPolicy: IfNotPresent
    name: jaeger-es-index-cleaner
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/proxy/htpasswd
      name: secret-htpasswd
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: trusted-ca-bundle
      readOnly: true
    - mountPath: /certs
      name: certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bb26x
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: jaeger-dockercfg-qr4tl
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000720000
    seLinuxOptions:
      level: s0:c27,c9
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: jaeger
  serviceAccountName: jaeger
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: secret-htpasswd
    secret:
      defaultMode: 420
      secretName: htpasswd
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: trusted-ca-bundle
      optional: true
    name: trusted-ca-bundle
  - name: certs
    secret:
      defaultMode: 420
      secretName: jaeger-curator
  - name: kube-api-access-bb26x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-25T23:55:00Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-25T23:55:00Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-25T23:55:00Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-25T23:55:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://d02efea2a51891d6cffae4903ff4fb1f8f15acd121157c4492c786ae6061acb1
    image: registry.redhat.io/rhosdt/jaeger-es-index-cleaner-rhel8@sha256:0065bf16da7fdf11c018388a4eb33349610129ea0465491d2bb6b24c275621dc
    imageID: registry.redhat.io/rhosdt/jaeger-es-index-cleaner-rhel8@sha256:0065bf16da7fdf11c018388a4eb33349610129ea0465491d2bb6b24c275621dc
    lastState: {}
    name: jaeger-es-index-cleaner
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: cri-o://d02efea2a51891d6cffae4903ff4fb1f8f15acd121157c4492c786ae6061acb1
        exitCode: 0
        finishedAt: "2023-03-25T23:55:07Z"
        reason: Completed
        startedAt: "2023-03-25T23:55:07Z"
  hostIP: 10.0.156.53
  phase: Succeeded
  podIP: 10.128.2.78
  podIPs:
  - ip: 10.128.2.78
  qosClass: Burstable
  startTime: "2023-03-25T23:55:00Z"
