- name: Install openshift servicemesh operators
  hosts: localhost
  tasks:
    - name: import static var data
      include_vars:
        dir: ./vars/static
        ignore_unknown_extensions: True
        extensions:
          - yaml
    
    - name: login to cluster
      community.okd.openshift_auth:
        username: "{{ username }}"
        password: "{{ password }}"
        host: "{{ apiserver }}"
        validate_certs: false
      register: ocp_auth_results

    - name: write the api key to dynamic vars
      copy:
        content: "api_key: {{ ocp_auth_results.openshift_auth.api_key | to_nice_yaml }}"
        dest: "vars/dynamic/main.yaml"

    - name: import dynamic var data
      include_vars:
        dir: ./vars/dynamic
        ignore_unknown_extensions: True
        extensions:
          - yaml

    - name: create openshift-operators-redhat namnespace
      kubernetes.core.k8s:
        name: "{{ operators.namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        api_key: "{{ api_key }}"  
    
    - name: create the operator group
      kubernetes.core.k8s:
        definition:
          api_version: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: "{{ operators.namespace }}"
            namespace: "{{ operators.namespace }}"
          spec: {}
        state: present
        api_key: "{{ api_key }}"

    - name: install elasticsearch operator
      include: ./tasks/es/install-es.yaml

    - name: install jaeger operator
      include: ./tasks/jaeger/install-jaeger.yaml

    - name: install kiali operator
      include: ./tasks/kiali/install-kiali.yaml

    - name: install openshift servicemesh operator
      include: ./tasks/istio/install-istio.yaml
      
    - name: install cert manager operator
      include: ./tasks/cert-manager/install-cert-manager.yaml  