---
apiVersion: apps/v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    annotations:
      deprecated.daemonset.template.generation: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"istio_cni","app.kubernetes.io/instance":"istio_cni","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"istio_cni","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"TODO","k8s-app":"istio-cni-node-v2-3","maistra-version":"2.3.2","maistra.io/owner":"","maistra.io/owner-name":"","release":"istio"},"name":"istio-cni-node-v2-3","namespace":"openshift-operators"},"spec":{"selector":{"matchLabels":{"k8s-app":"istio-cni-node-v2-3"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"k8s-app":"istio-cni-node-v2-3","release":"istio"}},"spec":{"containers":[{"command":["install-cni"],"env":[{"name":"CNI_CONF_NAME","value":"v2-3-istio-cni.conf"},{"name":"CNI_NETWORK_CONFIG","valueFrom":{"configMapKeyRef":{"key":"cni_network_config","name":"istio-cni-config-v2-3"}}},{"name":"CNI_NET_DIR","value":"/etc/cni/multus/net.d"},{"name":"CHAINED_CNI_PLUGIN","value":"false"},{"name":"MOUNTED_CNI_NET_DIR","value":"/host/etc/cni/multus/net.d"},{"name":"KUBECFG_FILE_NAME","value":"v2-3-istio-cni.kubeconfig"},{"name":"CNI_BINARIES_PREFIX","value":"v2-3-"}],"image":"registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:f967420e0e30c1193f6e766885e1e00a8a97e6929cf0d06cccd60649ff46610c","imagePullPolicy":null,"initialDelaySeconds":5,"livenessProbe":{"httpGet":{"path":"/healthz","port":8000}},"name":"install-cni","readinessProbe":{"httpGet":{"path":"/readyz","port":8000}},"resources":{"requests":{"cpu":"10m","memory":"100Mi"}},"securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/host/opt/cni/bin","name":"cni-bin-dir"},{"mountPath":"/host/etc/cni/","name":"etc-cni-dir"},{"mountPath":"/var/run/istio-cni","name":"cni-log-dir"}]}],"nodeSelector":{"kubernetes.io/os":"linux"},"priorityClassName":"system-node-critical","serviceAccountName":"istio-cni","terminationGracePeriodSeconds":5,"tolerations":[{"effect":"NoSchedule","operator":"Exists"},{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoExecute","operator":"Exists"}],"volumes":[{"hostPath":{"path":"/opt/multus/bin"},"name":"cni-bin-dir"},{"hostPath":{"path":"/etc/cni"},"name":"etc-cni-dir"},{"hostPath":{"path":"/var/run/istio-cni"},"name":"cni-log-dir"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":1},"type":"RollingUpdate"}}}
    creationTimestamp: "2023-03-24T10:12:56Z"
    generation: 2
    labels:
      app.kubernetes.io/component: istio_cni
      app.kubernetes.io/instance: istio_cni
      app.kubernetes.io/managed-by: maistra-istio-operator
      app.kubernetes.io/name: istio_cni
      app.kubernetes.io/part-of: istio
      app.kubernetes.io/version: TODO
      k8s-app: istio-cni-node-v2-3
      maistra-version: 2.3.2
      maistra.io/owner: ""
      maistra.io/owner-name: ""
      release: istio
    name: istio-cni-node-v2-3
    namespace: openshift-operators
    resourceVersion: "683577"
    uid: 7d34902b-b3e3-4617-a88d-3256a9bf7f59
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: istio-cni-node-v2-3
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
        creationTimestamp: null
        labels:
          k8s-app: istio-cni-node-v2-3
          release: istio
      spec:
        containers:
        - command:
          - install-cni
          env:
          - name: CNI_CONF_NAME
            value: v2-3-istio-cni.conf
          - name: CNI_NETWORK_CONFIG
            valueFrom:
              configMapKeyRef:
                key: cni_network_config
                name: istio-cni-config-v2-3
          - name: CNI_NET_DIR
            value: /etc/cni/multus/net.d
          - name: CHAINED_CNI_PLUGIN
            value: "false"
          - name: MOUNTED_CNI_NET_DIR
            value: /host/etc/cni/multus/net.d
          - name: KUBECFG_FILE_NAME
            value: v2-3-istio-cni.kubeconfig
          - name: CNI_BINARIES_PREFIX
            value: v2-3-
          image: registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:f967420e0e30c1193f6e766885e1e00a8a97e6929cf0d06cccd60649ff46610c
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: install-cni
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/
            name: etc-cni-dir
          - mountPath: /var/run/istio-cni
            name: cni-log-dir
        dnsPolicy: ClusterFirst
        nodeSelector:
          kubernetes.io/os: linux
        priorityClassName: system-node-critical
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: istio-cni
        serviceAccountName: istio-cni
        terminationGracePeriodSeconds: 5
        tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
        volumes:
        - hostPath:
            path: /opt/multus/bin
            type: ""
          name: cni-bin-dir
        - hostPath:
            path: /etc/cni
            type: ""
          name: etc-cni-dir
        - hostPath:
            path: /var/run/istio-cni
            type: ""
          name: cni-log-dir
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 6
    desiredNumberScheduled: 6
    numberAvailable: 6
    numberMisscheduled: 0
    numberReady: 6
    observedGeneration: 2
    updatedNumberScheduled: 6
kind: DaemonSetList
metadata:
  resourceVersion: "1903142"
