---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.2.176/23"],"mac_address":"0a:58:0a:81:02:b0","gateway_ips":["10.129.2.1"],"ip_address":"10.129.2.176/23","gateway_ip":"10.129.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.2.176"
          ],
          "mac": "0a:58:0a:81:02:b0",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.2.176"
          ],
          "mac": "0a:58:0a:81:02:b0",
          "default": true,
          "dns": {}
      }]
    linkerd.io/inject: disabled
    openshift.io/scc: restricted-v2
    prometheus.io/port: "14269"
    prometheus.io/scrape: "true"
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2023-03-24T17:29:17Z"
  generateName: jaeger-collector-6665599fc4-
  labels:
    app: jaeger
    app.kubernetes.io/component: collector
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-collector
    app.kubernetes.io/part-of: jaeger
    pod-template-hash: 6665599fc4
  name: jaeger-collector-6665599fc4-pxs52
  namespace: istio-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jaeger-collector-6665599fc4
    uid: d6e917fa-1b67-450b-ae7f-223f98b60c7e
  resourceVersion: "859901"
  uid: 6f434a85-2f14-4432-affa-c0fc669c028d
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  containers:
  - args:
    - --collector.grpc.tls.cert=/etc/tls-config/tls.crt
    - --collector.grpc.tls.enabled=true
    - --collector.grpc.tls.key=/etc/tls-config/tls.key
    - --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
    - --es.server-urls=https://elasticsearch:9200
    - --es.tls.enabled=true
    - --es.tls.ca=/certs/ca
    - --es.tls.cert=/certs/cert
    - --es.tls.key=/certs/key
    - --es.timeout=15s
    - --es.num-shards=3
    - --es.num-replicas=1
    env:
    - name: SPAN_STORAGE_TYPE
      value: elasticsearch
    - name: COLLECTOR_ZIPKIN_HOST_PORT
      value: :9411
    - name: COLLECTOR_OTLP_ENABLED
      value: "true"
    image: registry.redhat.io/rhosdt/jaeger-collector-rhel8@sha256:e04094d1c23e7f99d2c24078c85534d16740b240e75c3d36e53a7f24a6814913
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 14269
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 1
    name: jaeger-collector
    ports:
    - containerPort: 9411
      name: zipkin
      protocol: TCP
    - containerPort: 14267
      name: c-tchan-trft
      protocol: TCP
    - containerPort: 14268
      name: c-binary-trft
      protocol: TCP
    - containerPort: 14269
      name: admin-http
      protocol: TCP
    - containerPort: 14250
      name: grpc
      protocol: TCP
    - containerPort: 4317
      name: grpc-otlp
      protocol: TCP
    - containerPort: 4318
      name: http-otlp
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 14269
        scheme: HTTP
      initialDelaySeconds: 1
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000720000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/proxy/htpasswd
      name: secret-htpasswd
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: trusted-ca-bundle
      readOnly: true
    - mountPath: /etc/jaeger/sampling
      name: jaeger-sampling-configuration-volume
      readOnly: true
    - mountPath: /etc/tls-config
      name: jaeger-collector-tls-config-volume
      readOnly: true
    - mountPath: /certs
      name: certs
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-m9824
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  imagePullSecrets:
  - name: jaeger-dockercfg-qr4tl
  nodeName: ip-10-0-215-253.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000720000
    seLinuxOptions:
      level: s0:c27,c9
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: jaeger
  serviceAccountName: jaeger
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: secret-htpasswd
    secret:
      defaultMode: 420
      secretName: htpasswd
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: trusted-ca-bundle
      optional: true
    name: trusted-ca-bundle
  - configMap:
      defaultMode: 420
      items:
      - key: sampling
        path: sampling.json
      name: jaeger-sampling-configuration
    name: jaeger-sampling-configuration-volume
  - name: jaeger-collector-tls-config-volume
    secret:
      defaultMode: 420
      secretName: jaeger-collector-headless-tls
  - name: certs
    secret:
      defaultMode: 420
      secretName: jaeger-jaeger-elasticsearch
  - name: kube-api-access-m9824
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:29:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:29:19Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:29:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T17:29:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://0f2aabcf68f4590b6dfef926d4b8c6239f36713861a89e11f2f21948640f82f0
    image: registry.redhat.io/rhosdt/jaeger-collector-rhel8@sha256:e04094d1c23e7f99d2c24078c85534d16740b240e75c3d36e53a7f24a6814913
    imageID: registry.redhat.io/rhosdt/jaeger-collector-rhel8@sha256:e04094d1c23e7f99d2c24078c85534d16740b240e75c3d36e53a7f24a6814913
    lastState: {}
    name: jaeger-collector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T17:29:18Z"
  hostIP: 10.0.215.253
  phase: Running
  podIP: 10.129.2.176
  podIPs:
  - ip: 10.129.2.176
  qosClass: Burstable
  startTime: "2023-03-24T17:29:17Z"
