---
apiVersion: batch/v1
items:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    annotations:
      linkerd.io/inject: disabled
      prometheus.io/scrape: "false"
      sidecar.istio.io/inject: "false"
    creationTimestamp: "2023-03-24T17:29:17Z"
    generation: 1
    labels:
      app: jaeger
      app.kubernetes.io/component: cronjob-es-index-cleaner
      app.kubernetes.io/instance: jaeger
      app.kubernetes.io/managed-by: jaeger-operator
      app.kubernetes.io/name: jaeger-es-index-cleaner
      app.kubernetes.io/part-of: jaeger
    name: jaeger-es-index-cleaner
    namespace: istio-system
    ownerReferences:
    - apiVersion: jaegertracing.io/v1
      controller: true
      kind: Jaeger
      name: jaeger
      uid: a54859a0-fa66-4a80-a933-0b3891856e7b
    resourceVersion: "1672737"
    uid: fc7dd49a-44a8-410d-8ef3-39c1a2f5fe81
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        parallelism: 1
        template:
          metadata:
            annotations:
              linkerd.io/inject: disabled
              prometheus.io/scrape: "false"
              sidecar.istio.io/inject: "false"
            creationTimestamp: null
            labels:
              app: jaeger
              app.kubernetes.io/component: cronjob-es-index-cleaner
              app.kubernetes.io/instance: jaeger
              app.kubernetes.io/managed-by: jaeger-operator
              app.kubernetes.io/name: jaeger-es-index-cleaner
              app.kubernetes.io/part-of: jaeger
          spec:
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - preference:
                    matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                      - amd64
                  weight: 2
                - preference:
                    matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                      - ppc64le
                  weight: 2
                - preference:
                    matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                      - s390x
                  weight: 2
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: beta.kubernetes.io/arch
                      operator: In
                      values:
                      - amd64
                      - ppc64le
                      - s390x
            containers:
            - args:
              - "2"
              - https://elasticsearch:9200
              env:
              - name: SKIP_DEPENDENCIES
                value: "true"
              - name: ES_TLS_ENABLED
                value: "true"
              - name: ES_TLS_CA
                value: /certs/ca
              - name: ES_TLS_KEY
                value: /certs/key
              - name: ES_TLS_CERT
                value: /certs/cert
              - name: SHARDS
                value: "3"
              - name: REPLICAS
                value: "1"
              image: registry.redhat.io/rhosdt/jaeger-es-index-cleaner-rhel8@sha256:0065bf16da7fdf11c018388a4eb33349610129ea0465491d2bb6b24c275621dc
              imagePullPolicy: IfNotPresent
              name: jaeger-es-index-cleaner
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /etc/proxy/htpasswd
                name: secret-htpasswd
              - mountPath: /etc/pki/ca-trust/extracted/pem/
                name: trusted-ca-bundle
                readOnly: true
              - mountPath: /certs
                name: certs
                readOnly: true
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: jaeger
            serviceAccountName: jaeger
            terminationGracePeriodSeconds: 30
            volumes:
            - name: secret-htpasswd
              secret:
                defaultMode: 420
                secretName: htpasswd
            - configMap:
                defaultMode: 420
                items:
                - key: ca-bundle.crt
                  path: tls-ca-bundle.pem
                name: trusted-ca-bundle
                optional: true
              name: trusted-ca-bundle
            - name: certs
              secret:
                defaultMode: 420
                secretName: jaeger-curator
    schedule: 55 23 * * *
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    lastScheduleTime: "2023-03-25T23:55:00Z"
    lastSuccessfulTime: "2023-03-25T23:55:11Z"
kind: CronJobList
metadata:
  resourceVersion: "1903151"
