---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "opentelemetry.io/v1alpha1",
          "kind": "Instrumentation",
          "metadata": {
            "name": "instrumentation"
          },
          "spec": {
            "exporter": {
              "endpoint": "http://otel-collector-headless:4317"
            }
          }
        },
        {
          "apiVersion": "opentelemetry.io/v1alpha1",
          "kind": "OpenTelemetryCollector",
          "metadata": {
            "name": "otel"
          },
          "spec": {
            "config": "receivers:\n  otlp:\n    protocols: \n      grpc:\n      http:\n\nexporters:\n  logging:\n\nservice:\n  pipelines:\n    traces:\n      receivers: [otlp]\n      exporters: [logging]\n"
          }
        }
      ]
    capabilities: Basic Install
    categories: Logging & Tracing
    certified: "false"
    containerImage: registry.redhat.io/rhosdt/opentelemetry-rhel8-operator@sha256:9f9b22ffb73a9df02810db0524c4117f71d5b3333b937d6fae3f246a4e951abc
    createdAt: "2022-11-15 14:16:30.231922"
    description: Provides the OpenTelemetry components, including the Collector
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.2.27/23"],"mac_address":"0a:58:0a:80:02:1b","gateway_ips":["10.128.2.1"],"ip_address":"10.128.2.27/23","gateway_ip":"10.128.2.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.27"
          ],
          "mac": "0a:58:0a:80:02:1b",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.2.27"
          ],
          "mac": "0a:58:0a:80:02:1b",
          "default": true,
          "dns": {}
      }]
    olm.operatorGroup: global-operators
    olm.operatorNamespace: openshift-operators
    olm.skipRange: '>=0.33.0 <0.63.1-4'
    olm.targetNamespaces: ""
    olmcahash: 002512a8e4e24cdc424b047619e4b1b59d83cb60934a2ae6a12425309697c9c7
    openshift.io/scc: restricted-v2
    operatorframework.io/properties: '{"properties":[{"type":"olm.gvk","value":{"group":"opentelemetry.io","kind":"Instrumentation","version":"v1alpha1"}},{"type":"olm.gvk","value":{"group":"opentelemetry.io","kind":"OpenTelemetryCollector","version":"v1alpha1"}},{"type":"olm.package","value":{"packageName":"opentelemetry-product","version":"0.63.1-4"}}]}'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    repository: github.com/open-telemetry/opentelemetry-operator
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    support: Red Hat
  creationTimestamp: "2023-03-24T09:33:22Z"
  generateName: opentelemetry-operator-controller-manager-bfbf89c88-
  labels:
    app.kubernetes.io/name: opentelemetry-operator
    control-plane: controller-manager
    pod-template-hash: bfbf89c88
  name: opentelemetry-operator-controller-manager-bfbf89c88-n7k8g
  namespace: openshift-operators
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: opentelemetry-operator-controller-manager-bfbf89c88
    uid: a28434bf-4514-4887-b71d-c82e54634d6d
  resourceVersion: "636823"
  uid: 8512dd9b-42d1-4a1f-81b8-090f17988ddf
spec:
  containers:
  - args:
    - --metrics-addr=127.0.0.1:8080
    - --enable-leader-election
    - --zap-log-level=info
    - --zap-time-encoding=rfc3339nano
    - --collector-image=registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:281ebe43028f5c35912765b2867296a07606c12e352f931ad02de90ed32992e8
    env:
    - name: RELATED_IMAGE_OPENTELEMETRY_COLLECTOR
      value: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:281ebe43028f5c35912765b2867296a07606c12e352f931ad02de90ed32992e8
    - name: OPERATOR_CONDITION_NAME
      value: opentelemetry-operator.v0.63.1-4
    image: registry.redhat.io/rhosdt/opentelemetry-rhel8-operator@sha256:9f9b22ffb73a9df02810db0524c4117f71d5b3333b937d6fae3f246a4e951abc
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: manager
    ports:
    - containerPort: 9443
      name: webhook-server
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000400000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: webhook-cert
    - mountPath: /apiserver.local.config/certificates
      name: apiservice-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-spd42
      readOnly: true
  - args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    env:
    - name: OPERATOR_CONDITION_NAME
      value: opentelemetry-operator.v0.63.1-4
    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:f7993b7a5458679621f6686bdc4ab818659e051ef6cdf6a8e107f627adf5f178
    imagePullPolicy: IfNotPresent
    name: kube-rbac-proxy
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000400000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /apiserver.local.config/certificates
      name: apiservice-cert
    - mountPath: /tmp/k8s-webhook-server/serving-certs
      name: webhook-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-spd42
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: opentelemetry-operator-controller-manager-dockercfg-g55lq
  nodeName: ip-10-0-156-53.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000400000
    seLinuxOptions:
      level: s0:c20,c10
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: opentelemetry-operator-controller-manager
  serviceAccountName: opentelemetry-operator-controller-manager
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: cert
    secret:
      defaultMode: 420
      secretName: opentelemetry-operator-controller-manager-service-cert
  - name: apiservice-cert
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: apiserver.crt
      - key: tls.key
        path: apiserver.key
      secretName: opentelemetry-operator-controller-manager-service-cert
  - name: webhook-cert
    secret:
      defaultMode: 420
      items:
      - key: tls.crt
        path: tls.crt
      - key: tls.key
        path: tls.key
      secretName: opentelemetry-operator-controller-manager-service-cert
  - name: kube-api-access-spd42
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T09:33:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T09:33:58Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T09:33:58Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-03-24T09:33:22Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://219d91abe2dffccb3e589e713acea2c59a0d16e6a98055d2816349e2966ad28f
    image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:f7993b7a5458679621f6686bdc4ab818659e051ef6cdf6a8e107f627adf5f178
    imageID: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:1f0388e5fb4c96efbb2dacb5791aceee5d0df98378ed5f7c2b59c3307f3bda17
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T09:33:58Z"
  - containerID: cri-o://8492604376a1a96035f0c72d4ba260f4e00571750361475ffc51d38523de02b3
    image: registry.redhat.io/rhosdt/opentelemetry-rhel8-operator@sha256:9f9b22ffb73a9df02810db0524c4117f71d5b3333b937d6fae3f246a4e951abc
    imageID: registry.redhat.io/rhosdt/opentelemetry-rhel8-operator@sha256:8626897ef658db9491e2e7b5fd32bd42ac388be03ae5eb2980619edfdfecb056
    lastState: {}
    name: manager
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-03-24T09:33:40Z"
  hostIP: 10.0.156.53
  phase: Running
  podIP: 10.128.2.27
  podIPs:
  - ip: 10.128.2.27
  qosClass: Burstable
  startTime: "2023-03-24T09:33:22Z"
