apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"jaegertracing.io/v1","kind":"Jaeger","metadata":{"annotations":{"maistra.io/mesh-generation":"2.3.2-1-5"},"labels":{"app":"jaeger","app.kubernetes.io/component":"tracing","app.kubernetes.io/instance":"istio-system","app.kubernetes.io/managed-by":"maistra-istio-operator","app.kubernetes.io/name":"tracing","app.kubernetes.io/part-of":"istio","app.kubernetes.io/version":"2.3.2-1-5","maistra-version":"2.3.2","maistra.io/owner":"istio-system","maistra.io/owner-name":"basic","release":"istio"},"name":"jaeger","namespace":"istio-system","ownerReferences":[{"apiVersion":"maistra.io/v2","blockOwnerDeletion":true,"controller":true,"kind":"ServiceMeshControlPlane","name":"basic","uid":"ea62ab37-de81-47cf-a7a3-ecf2986a0b2f"}]},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["ppc64le"]}]},"weight":2},{"preference":{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["s390x"]}]},"weight":2}],"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","ppc64le","s390x"]}]}]}}},"ingress":{"enabled":true,"openshift":{"htpasswdFile":"/etc/proxy/htpasswd/auth","sar":"{\"namespace\": \"istio-system\", \"resource\": \"pods\", \"verb\": \"get\"}"},"security":"oauth-proxy"},"query":{"options":{"query":{"base-path":"/"}}},"resources":{"requests":{"cpu":"10m","memory":"128Mi"}},"storage":{"elasticsearch":{"nodeCount":3,"redundancyPolicy":"SingleRedundancy","resources":{"limits":{"cpu":"1","memory":"4Gi"},"requests":{"cpu":"1","memory":"4Gi"}},"storage":{"size":"50Gi","storageClassName":"gp2-csi"}},"esIndexCleaner":{"enabled":true,"numberOfDays":2,"schedule":"55 23 * * *"},"type":"elasticsearch"},"strategy":"production","volumeMounts":[{"mountPath":"/etc/proxy/htpasswd","name":"secret-htpasswd"},{"mountPath":"/etc/pki/ca-trust/extracted/pem/","name":"trusted-ca-bundle","readOnly":true}],"volumes":[{"name":"secret-htpasswd","secret":{"secretName":"htpasswd"}},{"configMap":{"defaultMode":420,"items":[{"key":"ca-bundle.crt","path":"tls-ca-bundle.pem"}],"name":"trusted-ca-bundle","optional":true},"name":"trusted-ca-bundle"}]}}
    maistra.io/mesh-generation: 2.3.2-1-5
  creationTimestamp: "2023-03-24T17:28:22Z"
  generation: 2
  labels:
    app: jaeger
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: istio-system
    app.kubernetes.io/managed-by: maistra-istio-operator
    app.kubernetes.io/name: tracing
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 2.3.2-1-5
    jaegertracing.io/operated-by: openshift-distributed-tracing.jaeger-operator
    maistra-version: 2.3.2
    maistra.io/owner: istio-system
    maistra.io/owner-name: basic
    release: istio
  name: jaeger
  namespace: istio-system
  ownerReferences:
  - apiVersion: maistra.io/v2
    blockOwnerDeletion: true
    controller: true
    kind: ServiceMeshControlPlane
    name: basic
    uid: ea62ab37-de81-47cf-a7a3-ecf2986a0b2f
  resourceVersion: "885903"
  uid: a54859a0-fa66-4a80-a933-0b3891856e7b
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - ppc64le
        weight: 2
      - preference:
          matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - s390x
        weight: 2
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: beta.kubernetes.io/arch
            operator: In
            values:
            - amd64
            - ppc64le
            - s390x
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    config: {}
    metricsStorage: {}
    options: {}
    resources: {}
  collector:
    config: {}
    kafkaSecretName: ""
    options: {}
    resources: {}
  ingester:
    config: {}
    kafkaSecretName: ""
    options: {}
    resources: {}
  ingress:
    enabled: true
    openshift:
      htpasswdFile: /etc/proxy/htpasswd/auth
      sar: '{"namespace": "istio-system", "resource": "pods", "verb": "get"}'
    options: {}
    resources: {}
    security: oauth-proxy
  query:
    metricsStorage: {}
    options:
      query:
        base-path: /
    resources: {}
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  sampling:
    options: {}
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
      schedule: 55 23 * * *
    elasticsearch:
      name: elasticsearch
      nodeCount: 3
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          cpu: "1"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 4Gi
      storage:
        size: 50Gi
        storageClassName: gp2-csi
    esIndexCleaner:
      enabled: true
      numberOfDays: 2
      resources: {}
      schedule: 55 23 * * *
    esRollover:
      resources: {}
      schedule: 0 0 * * *
    grpcPlugin: {}
    options: {}
    type: elasticsearch
  strategy: production
  ui:
    options:
      dependencies:
        menuEnabled: false
      menu:
      - items:
        - label: Documentation
          url: https://access.redhat.com/documentation/en-us/openshift_container_platform/4.9/html/distributed_tracing/index
        label: About
      - anchorTarget: _self
        label: Log Out
        url: /oauth/sign_in
  volumeMounts:
  - mountPath: /etc/proxy/htpasswd
    name: secret-htpasswd
  - mountPath: /etc/pki/ca-trust/extracted/pem/
    name: trusted-ca-bundle
    readOnly: true
  volumes:
  - name: secret-htpasswd
    secret:
      secretName: htpasswd
  - configMap:
      defaultMode: 420
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: trusted-ca-bundle
      optional: true
    name: trusted-ca-bundle
status:
  phase: Running
  version: 1.39.0
